#!/bin/sh               

#to be edited to point to the mrcc installation executable

ncpu=$2
echo $ncpu
export OMP_NUM_THREADS=$ncpu


SUB_DIR=`pwd`
rm -f /data/scratch/*
cp -f $3 /data/scratch/MINP
cd /data/scratch/

echo 'ok1'

# replace /software/dmrcc with the full path to mrcc executable
/software/dmrcc > $SUB_DIR/mrcc.log

for f in iface MOLDEN; do
 test -f /data/scratch/$f && cp /data/scratch/$f $SUB_DIR/
done

echo 'ok2'



